### ISSUE TITLE
I want to run the program and get same first half output

### ISSUE THREAD

**Issue by mkcreviews** [basil00/pairgen#7]
For example
first run will give 2 address 
ABCDmgkgktk
ABCDjdjfjfjfj

2nd run should give
ABCDnjgoktkrmdjd
ABCDmelofifjfjmfmfm

means ABCD should be there every time.
What changes shall I do in program to do this?? change seed or some logic or something else??
Please reply.

**Comment by basil00** [comment]
The algorithm `pairgen` uses has no control over the matching `ABCD` part, so it cannot be modified to generate more addresses with the same prefix.  For the latter, you could use a different tool (`vanitygen`) to get more addresses, however this takes a lot more computational power.
